version: '2'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: elasticsearch1
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet

  logstash1:
    image: docker.elastic.co/logstash/logstash:5.2.2
    container_name: logstash1
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - 5000:5000
    links:
      - elasticsearch1
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
