version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    #volumes:
    #  - ./kibana/.kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: changeme
    ports:
      - 5601:5601
    networks:
      - esnet
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    #command: elasticsearch -Des.network.host=0.0.0.0
    #container_name: elasticsearch1
    ports:
      - 9200:9200
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
    cap_add:
      - IPC_LOCK

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    #container_name: logstash1
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - 5000:5000
      - 5044:5044
    links:
      - elasticsearch
    networks:
      - esnet

  filebeat:
    image: prima/filebeat:5.2.2
    depends_on:
      #- elasticsearch
      - logstash
    hostname: filebeat
    networks:
      - esnet
    links:
      - logstash
    restart: unless-stopped
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - /var/lib/docker/containers:/hostfs/var/lib/docker/containers:rw
      #- /Users/paulvand/tmp:/hostfs/var/lib/docker/containers:rw

volumes:
  esdata1:
    driver: local

networks:
  esnet:
    driver: bridge
